baseUrl=https://qatest.paritycube.com
browser=chrome
implicitWait=5
explicitWait=20
adminEmail=admin@example.com
adminPassword=password123
staffEmail=staff@example.com
staffPassword=password123
invalidPassword=wrongPassword
